// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<ApkgParseResult> parseApkg({required String path}) =>
    RustLib.instance.api.crateApiSimpleParseApkg(path: path);

class ApkgParseResult {
  final List<Note> notes;
  final Map<String, String> mediaMap;
  final Map<String, Uint8List> mediaFiles;

  const ApkgParseResult({
    required this.notes,
    required this.mediaMap,
    required this.mediaFiles,
  });

  @override
  int get hashCode => notes.hashCode ^ mediaMap.hashCode ^ mediaFiles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApkgParseResult &&
          runtimeType == other.runtimeType &&
          notes == other.notes &&
          mediaMap == other.mediaMap &&
          mediaFiles == other.mediaFiles;
}

class Note {
  final PlatformInt64 id;
  final String guid;
  final PlatformInt64 mid;
  final List<String> flds;

  const Note({
    required this.id,
    required this.guid,
    required this.mid,
    required this.flds,
  });

  @override
  int get hashCode =>
      id.hashCode ^ guid.hashCode ^ mid.hashCode ^ flds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Note &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          guid == other.guid &&
          mid == other.mid &&
          flds == other.flds;
}
